# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-10 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '主机组', 'verbose_name_plural': '主机组'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': '维护', 'verbose_name_plural': '维护'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '监控项', 'verbose_name_plural': '监控项'},
        ),
        migrations.AlterModelOptions(
            name='serviceitem',
            options={'verbose_name': '服务指标', 'verbose_name_plural': '服务指标'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': '模板', 'verbose_name_plural': '模板'},
        ),
        migrations.AlterModelOptions(
            name='trigger',
            options={'verbose_name': '触发器', 'verbose_name_plural': '触发器'},
        ),
    ]
